---
# tasks file for apache2
- name: Load the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the apache packages
  package: 
    name: '{{ apache_pkgs }}'
    state: present

- name: Get apache version
  check_mode: false
  changed_when: false
  shell: '{{ apache_service | quote }} -v | grep version | sed -e "s/Server version.\{1\} Apache\/\([0-9]\)\.\([0-9]\)\.\([0-9]\{1,3\}\).*/\1.\2/g"'
  register: apache_version

- name: Get apache subversion
  check_mode: false
  changed_when: false
  shell: '{{ apache_service | quote }} -v | grep version | sed -e "s/Server version.\{1\} Apache\/\([0-9]\)\.\([0-9]\)\.\([0-9]\{1,3\}\).*/\3/g"'
  register: apache_subversion

- name: Load additional variables
  include_vars: "{{ ansible_os_family }}-{{ apache_version.stdout }}.yml"

- name: Load security hardening for apache
  copy: src=conf.d/{{ item }} dest={{ apache_conf_d_dir }} owner=root group=root mode=0644 backup=yes
  loop: 
    - "deflate.conf"
    - "etag.conf"
    - "security.conf"
  notify: reload apache

- name: Enable loaded security configuration on Debian family
  command: /usr/sbin/a2enconf {{ item }} creates=/etc/apache2/mods-enabled/{{ item + '.load' }}
  loop: 
    - "deflate.conf"
    - "etag.conf"
    - "security.conf"
  when: 
    - ansible_os_family == 'Debian'
  notify: reload apache

- name: Enable aditional apache modules if needed
  apache2_module:
    name: "{{ item }}"
  loop: '{{ apache_modules }}'
  when: 
    - ansible_os_family == 'Debian'
    - apache_modules is defined
  notify: reload apache

- name: Ensure http/2 module is loaded on new enough apache version on Debian family
  apache2_module: 
    name: http2
    state: present
  when: 
    - ansible_os_family == 'Debian'
    - apache_version.stdout == '2.4'
    - apache_subversion.stdout|int >= 17
  notify: reload apache

- name: Load apache configuration
  template: src=apache2.conf.{{ ansible_os_family }}-{{ apache_version.stdout }}.j2 dest={{ apache_conf_dir }}/{{ apache_config_file }} owner=root group=root mode=0644 backup=yes
  notify: reload apache

- name: Load ports configuration (Listen directive)
  template: src=ports.conf.j2 dest={{ apache_conf_dir }}/ports.conf owner=root group=root mode=0644
  notify: restart apache
  when: ansible_os_family == 'Debian'

- name: Ensure all not used MPMs are disabled (Debian)
  apache2_module:
    name: "mpm_{{ item }}"
    state: absent
  loop:
    - "worker"
    - "prefork"
    - "event"
  when: 
    - "apache2_mpm != item"
    - ansible_os_family == "Debian"
  # Apache fails when no mpm is present, but it also fails when we want to have second one
  # So ignored here, next task set up mpm
  failed_when: false
  notify: reload apache

- name: Ensure proper mpm is active
  apache2_module: 
    name: "mpm_{{ apache2_mpm }}"
    state: present
  when: 
    - ansible_os_family == "Debian"
  notify: reload apache


- name: Ensure proper mpm is activated (apache 2.4)
  template:
    src: '00-mpm.conf.j2'
    dest: '{{ apache_modules_dir }}/00-mpm.conf'
  when:
    - apache_version.stdout == '2.4'
    - ansible_os_family == 'RedHat'
  notify: restart apache

- name: Ensure vhosts.d directory is defined (RedHat)
  file: path={{ apache_vhosts_conf_dir }} state=directory owner=root group=root mode=0750
  when: ansible_os_family == 'RedHat'

- name: Ensure default vhost is available
  template: 
    src: default.j2
    dest: "{{ apache_vhosts_conf_dir + '/000-default.conf' }}"
    backup: true
  when: apache_default_vhost_enabled

- name: Ensure default SSL configuration is safe
  template: 
    src: "{{ apache_ssl_file + '.' + ansible_os_family + '.j2' }}"
    dest: "{{ apache2_ssl_dir + '/' + apache_ssl_file }}"
    seuser: "system_u"
    serole: "object_r"
    setype: "httpd_config_t"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: "yes"
  notify: reload apache

- name: Upload acme alias if acme enabled
  template:
    src: acme.conf.j2
    dest: "{{ apache_conf_d_dir + '/acme.conf' }}"
    owner: "root"
    group: "root"
    mode: "0644"
    seuser: "system_u"
    serole: "object_r"
    setype: "httpd_config_t"
    backup: yes
  notify: reload apache

- name: Ensure apache is running and autostart
  service: name={{ apache_service }} state=started enabled=yes

